// =========================================================================
// Queensland Transport Route Data
// =========================================================================
//
// Current routes (suburban rail, bus, ferry, tram) → public/gtfs-routes.json
// Proposed routes, Olympic fixes, problem areas  → public/proposed-routes.json
//
// This file holds:
//  - Static regional-rail & freight corridors (not in GTFS)
//  - Layer colour / label / config constants
// 
// Generated by AI Currently TBC
// =========================================================================

export type RouteMode =
  | 'rail'
  | 'bus'
  | 'ferry'
  | 'tram'
  | 'regional-rail'
  | 'freight'
  | 'proposed-rail'
  | 'proposed-bus'
  | 'proposed-ferry'
  | 'proposed-regional-rail'
  | 'olympic-fix'
  | 'problem-area'
  | 'high-speed-rail'

/* ------------------------------------------------------------------ */
/*  Static current network (regional passenger rail & freight only)     */
/*  Suburban rail / bus / ferry / tram come from GTFS JSON at runtime.  */
/* ------------------------------------------------------------------ */

export const staticRoutes: GeoJSON.FeatureCollection = {
  type: 'FeatureCollection',
  features: [
    // ===== REGIONAL PASSENGER RAIL =====
    {
      type: 'Feature',
      properties: {
        name: 'Spirit of Queensland (Brisbane–Cairns)',
        mode: 'regional-rail',
        description:
          'Long-distance tilt train service from Roma Street to Cairns, stopping at major towns along the North Coast Line. ~1,680 km, approximately 24 hours.',
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [153.0235, -27.4679], // Brisbane
          [153.0002, -27.2353], // Caboolture
          [153.0607, -26.6867], // Nambour
          [153.0184, -26.388], // Gympie
          [152.702, -25.519], // Bundaberg
          [150.513, -23.378], // Rockhampton
          [149.186, -21.142], // Mackay
          [146.788, -19.257], // Townsville
          [145.778, -16.923], // Cairns
        ],
      },
    },
    {
      type: 'Feature',
      properties: {
        name: 'Spirit of the Outback (Brisbane–Longreach)',
        mode: 'regional-rail',
        description:
          'Twice-weekly service from Brisbane across the Great Dividing Range to Longreach via Rockhampton and Emerald. ~1,325 km.',
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [153.0235, -27.4679], // Brisbane
          [150.513, -23.378], // Rockhampton
          [148.162, -23.437], // Emerald
          [144.25, -23.432], // Longreach
        ],
      },
    },
    {
      type: 'Feature',
      properties: {
        name: 'Westlander (Brisbane–Charleville)',
        mode: 'regional-rail',
        description:
          'Twice-weekly service from Brisbane to Charleville via Toowoomba and the Darling Downs. ~777 km.',
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [153.0235, -27.4679], // Brisbane
          [152.7666, -27.612], // Ipswich
          [151.951, -27.561], // Toowoomba
          [151.27, -27.56], // Dalby
          [150.512, -27.555], // Miles
          [149.775, -27.553], // Roma
          [146.243, -26.407], // Charleville
        ],
      },
    },
    {
      type: 'Feature',
      properties: {
        name: 'Inlander (Townsville–Mount Isa)',
        mode: 'regional-rail',
        description:
          'Twice-weekly service crossing North Queensland from Townsville to Mount Isa. ~977 km, approximately 21 hours.',
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [146.788, -19.257], // Townsville
          [146.258, -19.268], // Charters Towers
          [144.515, -20.069], // Hughenden
          [141.471, -20.713], // Cloncurry
          [139.493, -20.726], // Mount Isa
        ],
      },
    },
    {
      type: 'Feature',
      properties: {
        name: 'Kuranda Scenic Railway',
        mode: 'regional-rail',
        description:
          'Heritage and tourist railway winding from Cairns through rainforest and gorge country to Kuranda. 37 km.',
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [145.778, -16.923], // Cairns
          [145.746, -16.889], // Redlynch
          [145.669, -16.854], // Kuranda
        ],
      },
    },

    // ===== FREIGHT CORRIDORS =====
    {
      type: 'Feature',
      properties: {
        name: 'North Coast Line (Freight)',
        mode: 'freight',
        description:
          'Major freight corridor from Brisbane to Cairns carrying bulk commodities, containers, and intermodal freight. Shared with passenger services on much of its length.',
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [153.0235, -27.4679], // Brisbane
          [153.0002, -27.2353], // Caboolture
          [153.0607, -26.6867], // Nambour
          [152.702, -25.519], // Bundaberg
          [152.347, -24.867], // Gladstone
          [150.513, -23.378], // Rockhampton
          [149.186, -21.142], // Mackay
          [148.26, -20.017], // Bowen
          [146.788, -19.257], // Townsville
          [146.03, -18.18], // Ingham
          [145.929, -17.519], // Innisfail
          [145.778, -16.923], // Cairns
        ],
      },
    },
    {
      type: 'Feature',
      properties: {
        name: 'Western Line (Freight)',
        mode: 'freight',
        description:
          'Freight corridor from Ipswich west through Toowoomba and the Darling Downs grain belt to Charleville. Key route for agricultural exports.',
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [153.0235, -27.4679], // Brisbane / Acacia Ridge
          [152.7666, -27.612], // Ipswich
          [152.37, -27.58], // Laidley
          [151.951, -27.561], // Toowoomba
          [151.27, -27.56], // Dalby
          [150.512, -27.555], // Miles
          [149.775, -27.553], // Roma
          [146.243, -26.407], // Charleville
        ],
      },
    },
    {
      type: 'Feature',
      properties: {
        name: 'Moura Short Line (Coal)',
        mode: 'freight',
        description:
          `Dedicated coal freight line from the Moura and Callide mines to the port of Gladstone. One of Queensland's key coal export corridors.`,
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [152.347, -24.867], // Gladstone
          [151.7, -24.63], // Calliope
          [150.44, -24.57], // Moura
        ],
      },
    },
    {
      type: 'Feature',
      properties: {
        name: 'Goonyella & Newlands (Coal)',
        mode: 'freight',
        description:
          'Major coal export systems in the Bowen Basin, linking mines to Dalrymple Bay / Hay Point and Abbot Point coal terminals near Mackay and Bowen.',
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [149.186, -21.142], // Mackay / Hay Point
          [148.89, -21.32], // Coppabella
          [148.44, -21.64], // Moranbah
          [148.08, -21.8], // Peak Downs
        ],
      },
    },
    {
      type: 'Feature',
      properties: {
        name: 'Mount Isa Line (Minerals)',
        mode: 'freight',
        description:
          'Critical freight corridor from Townsville to Mount Isa carrying zinc, lead, copper, and other minerals. Also serves the Inlander passenger service.',
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [146.788, -19.257], // Townsville
          [146.258, -19.268], // Charters Towers
          [144.515, -20.069], // Hughenden
          [141.471, -20.713], // Cloncurry
          [139.493, -20.726], // Mount Isa
        ],
      },
    },
    {
      type: 'Feature',
      properties: {
        name: 'Acacia Ridge Intermodal Terminal',
        mode: 'freight',
        description:
          `Major intermodal freight terminal in Brisbane's south. Hub for interstate rail freight and container transfers.`,
      },
      geometry: {
        type: 'LineString',
        coordinates: [
          [153.0235, -27.4679], // Brisbane
          [153.035, -27.495],
          [153.048, -27.531],
          [153.049, -27.562], // Acacia Ridge area
        ],
      },
    },
  ],
}

/* ------------------------------------------------------------------ */
/*  Layer configuration                                                */
/* ------------------------------------------------------------------ */

export const LAYER_COLORS: Record<string, string> = {
  rail: '#1d4ed8',
  bus: '#16a34a',
  ferry: '#0891b2',
  tram: '#d97706',
  'regional-rail': '#7e22ce',
  freight: '#78716c',
  'proposed-rail': '#dc2626',
  'proposed-bus': '#ea580c',
  'proposed-ferry': '#6d28d9',
  'proposed-regional-rail': '#be123c',
  'olympic-fix': '#ca8a04',
  'problem-area': '#ef4444',
  'high-speed-rail': '#0ea5e9',
}

export type LayerKey =
  | 'currentRail'
  | 'currentBus'
  | 'currentFerry'
  | 'currentTram'
  | 'currentRegionalRail'
  | 'currentFreight'
  | 'proposedRail'
  | 'proposedBus'
  | 'proposedFerry'
  | 'proposedRegionalRail'
  | 'olympicFixes'
  | 'problemAreas'
  | 'highSpeedRail'

export const LAYER_LABELS: Record<LayerKey, string> = {
  currentRail: 'Suburban Rail',
  currentBus: 'Bus Routes',
  currentFerry: 'Ferry Routes',
  currentTram: 'Light Rail / Tram',
  currentRegionalRail: 'Regional Passenger Rail',
  currentFreight: 'Freight Corridors',
  proposedRail: 'Proposed Rail',
  proposedBus: 'Proposed Busways / BRT',
  proposedFerry: 'Proposed Ferry',
  proposedRegionalRail: 'Proposed Regional Rail',
  olympicFixes: 'Olympic Fixes (2032)',
  problemAreas: 'Problem Areas',
  highSpeedRail: 'High Speed Rail',
}

export const LAYER_CSS_COLORS: Record<LayerKey, string> = {
  currentRail: 'bg-blue-700',
  currentBus: 'bg-green-600',
  currentFerry: 'bg-cyan-600',
  currentTram: 'bg-amber-600',
  currentRegionalRail: 'bg-purple-700',
  currentFreight: 'bg-stone-500',
  proposedRail: 'bg-red-600',
  proposedBus: 'bg-orange-600',
  proposedFerry: 'bg-violet-700',
  proposedRegionalRail: 'bg-rose-700',
  olympicFixes: 'bg-yellow-600',
  problemAreas: 'bg-red-500',
  highSpeedRail: 'bg-sky-500',
}

/** Map from LayerKey to MapLibre layer id */
export const LAYER_ID_MAP: Record<LayerKey, string> = {
  currentRail: 'current-rail',
  currentBus: 'current-bus',
  currentFerry: 'current-ferry',
  currentTram: 'current-tram',
  currentRegionalRail: 'current-regional-rail',
  currentFreight: 'current-freight',
  proposedRail: 'proposed-rail',
  proposedBus: 'proposed-bus',
  proposedFerry: 'proposed-ferry',
  proposedRegionalRail: 'proposed-regional-rail',
  olympicFixes: 'olympic-fix',
  problemAreas: 'problem-area',
  highSpeedRail: 'high-speed-rail',
}
